version: "3.7"

services:
  tkstats:
    build: .
    image: tkstats:latest
    environment:
      - DATABASE_FILE=/data/tkstats.db
    restart: always
    ports:
      - 3031:3031
    volumes:
      - ./tkstats.db:/data/tkstats.db
